# Start from the alpine image
FROM devopsdockeruh/simple-web-service:alpine

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

CMD server
