version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5000:5000
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
